apiVersion: batch/v1
kind: Job
metadata:
  label:
    app: jmeter-docker
  name: jmeter-docker
spec:
  activeDeadlineSeconds: 300
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: pi
    spec:
      containers:
      - name: jmeter-docker
        image: jmeter-docker
      restartPolicy: OnFailure    